In [2]:
import pandas as pd
import numpy as np

Creating a [DataFrame](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame) by passing a NumPy array with a datetime index using [date_range()](https://pandas.pydata.org/docs/reference/api/pandas.date_range.html#pandas.date_range) and labeled columns:

In [3]:
dates = pd.date_range("20260601", periods=6)

In [4]:
dates

DatetimeIndex(['2026-06-01', '2026-06-02', '2026-06-03', '2026-06-04',
               '2026-06-05', '2026-06-06'],
              dtype='datetime64[ns]', freq='D')

In [5]:
df = pd.DataFrame(np.random.randn(6, 4),
                  index=dates,
                  columns=list("ABCD"))

In [6]:
df

                   A         B         C         D
2026-06-01 -0.661068  1.072577 -0.250244 -1.909540
2026-06-02  1.107722 -1.899317 -0.864275  0.687182
2026-06-03 -2.976820 -0.005608  1.046609 -0.022708
2026-06-04 -1.215148  0.459604  0.964917 -0.929091
2026-06-05  0.959283  0.046251  1.186689 -0.189859
2026-06-06 -0.053743 -0.432084  1.200853 -0.045622

In [7]:
cols = {
    "A": 1.0,
    "B": pd.Timestamp("20260613"),
    "C": pd.Series(1, index=list(range(4)), dtype="float32"),
    "D": np.array([3, 3, 3, 3], dtype="int32"),
    "E": pd.Categorical(["test", "train", "test", "train"]),
    "F": "foo"
    }

In [8]:
df2 = pd.DataFrame(cols)

In [9]:
df2

     A          B    C  D      E    F
0  1.0 2026-06-13  1.0  3   test  foo
1  1.0 2026-06-13  1.0  3  train  foo
2  1.0 2026-06-13  1.0  3   test  foo
3  1.0 2026-06-13  1.0  3  train  foo

In [10]:
df2.dtypes

A          float64
B    datetime64[s]
C          float32
D            int32
E         category
F           object
dtype: object

In [11]:
df.head()

                   A         B         C         D
2026-06-01 -0.661068  1.072577 -0.250244 -1.909540
2026-06-02  1.107722 -1.899317 -0.864275  0.687182
2026-06-03 -2.976820 -0.005608  1.046609 -0.022708
2026-06-04 -1.215148  0.459604  0.964917 -0.929091
2026-06-05  0.959283  0.046251  1.186689 -0.189859

In [12]:
df.tail(3)

                   A         B         C         D
2026-06-04 -1.215148  0.459604  0.964917 -0.929091
2026-06-05  0.959283  0.046251  1.186689 -0.189859
2026-06-06 -0.053743 -0.432084  1.200853 -0.045622

In [13]:
df.index

DatetimeIndex(['2026-06-01', '2026-06-02', '2026-06-03', '2026-06-04',
               '2026-06-05', '2026-06-06'],
              dtype='datetime64[ns]', freq='D')

In [14]:
df.to_numpy()

array([[-0.66106801,  1.07257652, -0.25024436, -1.90953963],
       [ 1.10772235, -1.89931659, -0.86427509,  0.68718169],
       [-2.97682028, -0.0056079 ,  1.04660926, -0.02270849],
       [-1.21514784,  0.45960444,  0.96491724, -0.92909075],
       [ 0.95928257,  0.04625092,  1.18668868, -0.18985945],
       [-0.05374341, -0.43208388,  1.20085326, -0.04562175]])

In [15]:
df2.to_numpy()

array([[1.0, Timestamp('2026-06-13 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2026-06-13 00:00:00'), 1.0, 3, 'train', 'foo'],
       [1.0, Timestamp('2026-06-13 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2026-06-13 00:00:00'), 1.0, 3, 'train', 'foo']],
      dtype=object)

In [16]:
df.describe()

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.473296 -0.126429  0.547425 -0.401606
std    1.521917  1.006183  0.881849  0.900299
min   -2.976820 -1.899317 -0.864275 -1.909540
25%   -1.076628 -0.325465  0.053546 -0.744283
50%   -0.357406  0.020322  1.005763 -0.117741
75%    0.706026  0.356266  1.151669 -0.028437
max    1.107722  1.072577  1.200853  0.687182

In [17]:
df.T

   2026-06-01  2026-06-02  2026-06-03  2026-06-04  2026-06-05  2026-06-06
A   -0.661068    1.107722   -2.976820   -1.215148    0.959283   -0.053743
B    1.072577   -1.899317   -0.005608    0.459604    0.046251   -0.432084
C   -0.250244   -0.864275    1.046609    0.964917    1.186689    1.200853
D   -1.909540    0.687182   -0.022708   -0.929091   -0.189859   -0.045622

In [19]:
df.sort_index(axis=1, ascending=True)

                   A         B         C         D
2026-06-01 -0.661068  1.072577 -0.250244 -1.909540
2026-06-02  1.107722 -1.899317 -0.864275  0.687182
2026-06-03 -2.976820 -0.005608  1.046609 -0.022708
2026-06-04 -1.215148  0.459604  0.964917 -0.929091
2026-06-05  0.959283  0.046251  1.186689 -0.189859
2026-06-06 -0.053743 -0.432084  1.200853 -0.045622

In [20]:
df.sort_values(by="B")

                   A         B         C         D
2026-06-02  1.107722 -1.899317 -0.864275  0.687182
2026-06-06 -0.053743 -0.432084  1.200853 -0.045622
2026-06-03 -2.976820 -0.005608  1.046609 -0.022708
2026-06-05  0.959283  0.046251  1.186689 -0.189859
2026-06-04 -1.215148  0.459604  0.964917 -0.929091
2026-06-01 -0.661068  1.072577 -0.250244 -1.909540

In [36]:
df2["G"] = ["zero", "one", "two", "three"]
df2

     A          B    C  D      E    F      G
0  1.0 2026-06-13  1.0  3   test  foo   zero
1  1.0 2026-06-13  1.0  3  train  foo    one
2  1.0 2026-06-13  1.0  3   test  foo    two
3  1.0 2026-06-13  1.0  3  train  foo  three

In [35]:
df2[["G", "F"]]

       G    F
0   zero  foo
1    one  foo
2    two  foo
3  three  foo

In [52]:
df2.iloc[0:2, 0:3]

     A          B    C
0  1.0 2026-06-13  1.0
1  1.0 2026-06-13  1.0